esphome:
  name: garage_door
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "XXXXXXXXX"
  password: "XXXXXXXXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Door Fallback Hotspot"
    password: "XXXXXXXXX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

globals:
  - id: performing_last_movement
    type: boolean
    restore_value: no
    initial_value: 'false'

switch:
  # The switch that turns the UP direction on
  - platform: gpio
    pin: D1
    id: garage_switch
    # If ESP reboots, do not attempt to restore switch state
    restore_mode: always off

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: true
    name: "Garage Closed Reed Switch"
    id: closed_endstop
    filters:
      - delayed_on: 1000ms #Wait to stop moving
      - delayed_off: 1000ms #Wait to start moving
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: true
    name: "Garage Open Reed Switch"
    id: open_endstop
    filters:
      - delayed_on: 1000ms #Wait to stop moving
      - delayed_off: 1000ms #Wait to start moving

cover:
  - platform: template
    name: "Garage Door"
    id: garage_door
    device_class: garage
    assumed_state: true
    lambda: !lambda |-
      if (id(closed_endstop).state) //Door just hit closed endstop
      { 
        if(id(garage_door).current_operation ==  esphome::cover::COVER_OPERATION_OPENING) //We should be opening
        {
          if(!id(performing_last_movement)) //Make sure we don't trigger thi slogic twice otherwise it will do unwanted things
          {
            delay(1000); //Wait for door to stop in case reed is triggered too early
            id(garage_switch).turn_on(); //Press button again
            delay(500);
            id(garage_switch).turn_off();
            id(performing_last_movement) = true; //Set flag to indicate we madeknow where the door is
          }
        }
        else if(id(garage_door).current_operation ==  esphome::cover::COVER_OPERATION_CLOSING)
        {
          //We should be closing, so all is good
          id(performing_last_movement) = false;
          id(garage_door).current_operation =  esphome::cover::COVER_OPERATION_IDLE;
          return COVER_CLOSED;
        }
        else
        {
          //No operation in progress, just send state
          id(performing_last_movement) = false;
          return COVER_CLOSED;
        }
      }
      else if (id(open_endstop).state) //Door just hit open endstop
      {
        if(id(garage_door).current_operation ==  esphome::cover::COVER_OPERATION_CLOSING) //We should be closing
        {
          if (!id(performing_last_movement))  //Make sure we don't trigger thi slogic twice otherwise it will do unwanted things
          {
            delay(1000);  //Wait for door to stop in case reed is triggered too early
            id(garage_switch).turn_on(); //Press button again
            delay(500);
            id(garage_switch).turn_off();
            id(performing_last_movement) = true; //Set flag to indicate we madeknow where the door is
          }
        }
        else if(id(garage_door).current_operation ==  esphome::cover::COVER_OPERATION_OPENING)
        {
          //We should be opening, so all is good
          id(performing_last_movement) = false;
          id(garage_door).current_operation =  esphome::cover::COVER_OPERATION_IDLE;
          return COVER_OPEN;
        }
        else
        {
          //No operation in progress, just send state
          id(performing_last_movement) = false;
          return COVER_OPEN;
        }
      }

    open_action: 
      - lambda: !lambda |-
          id(garage_door).current_operation =  esphome::cover::COVER_OPERATION_OPENING;
          if (!id(open_endstop).state) {
            id(garage_switch).turn_on();
            delay(500);
            id(garage_switch).turn_off();
            if (id(closed_endstop).state) {
              id(performing_last_movement) = true; //Set flag to indicate we know where the door is
            }
          }
    close_action:
      - lambda: !lambda |-
          id(garage_door).current_operation =  esphome::cover::COVER_OPERATION_CLOSING;
          if (!id(closed_endstop).state) {
            id(garage_switch).turn_on();
            delay(500);
            id(garage_switch).turn_off();
            if (id(open_endstop).state) {
              id(performing_last_movement) = true; //Set flag to indicate we know where the door is
            }
          }
    stop_action:
      - lambda: !lambda |-
          if(id(garage_door).current_operation ==  esphome::cover::COVER_OPERATION_CLOSING || id(garage_door).current_operation ==  esphome::cover::COVER_OPERATION_OPENING )
          {
            id(garage_door).current_operation =  esphome::cover::COVER_OPERATION_IDLE;
            //Stop the door if it is moving
            id(performing_last_movement) = false;
            id(garage_switch).turn_on();
            delay(500);
            id(garage_switch).turn_off();
          }
